version: '3'
services:
# Nginx
  nginx:
    build: ./nginx
    volumes:
        - .:/usr/src/app
    links:
        - django
    ports:
        - "80:80"
    restart: always      

# This defines a service for the Django app
  django:
    build: .
    volumes:
        - .:/usr/src/app
    expose:
        - "8000"
    links:
        - postgres


# This defines a service for the Postgres database
  postgres:
    image: postgres:10.5
  