# Generated by Django 2.1 on 2018-12-13 09:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_transport', '0002_remove_agenttransport_ref'),
        ('booking', '0005_auto_20181106_1733'),
        ('customer', '0003_remove_shipper_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_customer', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_title', models.CharField(blank=True, max_length=50, null=True)),
                ('optional', models.CharField(blank=True, max_length=5, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerforms', to='customer.Principal')),
            ],
        ),
        migrations.CreateModel(
            name='FormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=50, null=True)),
                ('form_detail', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15, null=True), size=4)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=15, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('1', 'Finished'), ('0', 'Processing')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Invoice')),
                ('work_agent_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_transport.AgentTransport')),
                ('work_normal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_billing', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Finished'), ('0', 'Processing')], default=0, max_length=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.CustomerForm')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, max_length=2, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('diesel_rate_of_week', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(choices=[('1', 'Finished'), ('0', 'Processing')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='summaryweek',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Year'),
        ),
        migrations.AddField(
            model_name='summarycustomer',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.SummaryWeek'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.SummaryCustomer'),
        ),
        migrations.AddField(
            model_name='customerform',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.FormDetail'),
        ),
    ]
