# Generated by Django 2.1 on 2019-01-04 04:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_shipper_address'),
        ('summary', '0002_auto_20181225_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerForm',
            new_name='CustomerCustom',
        ),
        migrations.RenameField(
            model_name='customercustom',
            old_name='optional',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='drayage_total',
        ),
        migrations.RenameField(
            model_name='summaryweek',
            old_name='diesel_rate_of_week',
            new_name='diesel_rate',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='name',
            new_name='year_label',
        ),
        migrations.AddField(
            model_name='invoice',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='gate_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='drayage_charge',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='gate_charge',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summarycustomer',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('0', 'Processing'), ('1', 'Finished')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='summarycustomer',
            name='status',
            field=models.CharField(choices=[('0', 'Processing'), ('1', 'Finished')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='summaryweek',
            name='status',
            field=models.CharField(choices=[('0', 'Processing'), ('1', 'Finished')], default=0, max_length=1),
        ),
    ]
