# Generated by Django 2.1 on 2019-01-04 04:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20190104_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='drayage_charge',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='gate_charge',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
