# Generated by Django 2.1 on 2019-01-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_auto_20190104_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercustom',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customercustoms', to='customer.Principal'),
        ),
    ]
