# Generated by Django 2.1 on 2019-01-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_auto_20190121_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
