# Generated by Django 2.1 on 2019-01-22 07:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_auto_20190121_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetail',
            name='form_detail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15, null=True), size=10),
        ),
    ]
