# Generated by Django 2.2 on 2019-05-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_invoicesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercustom',
            name='option',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
