# Generated by Django 2.2 on 2019-06-05 10:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_auto_20190507_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarycustomer',
            old_name='date_end',
            new_name='date_due',
        ),
        migrations.RemoveField(
            model_name='summarycustomer',
            name='detail',
        ),
        migrations.AddField(
            model_name='summarycustomer',
            name='date_accept',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarycustomer',
            name='remark',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
