# Generated by Django 2.2 on 2019-06-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_auto_20190605_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarycustomer',
            old_name='remark',
            new_name='detail',
        ),
    ]
