# Generated by Django 2.2 on 2020-04-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_auto_20190605_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceSetting',
        ),
    ]
