# Generated by Django 2.0.7 on 2018-07-17 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('principal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Principal')),
            ],
        ),
    ]
