# Generated by Django 2.0.7 on 2018-07-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180717_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='shipper_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
