# Generated by Django 2.0.7 on 2018-07-17 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180717_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='principal_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Principal'),
        ),
    ]
