# Generated by Django 2.0.7 on 2018-07-17 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180717_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='principal_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='principal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Principal'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
