# Generated by Django 2.0.7 on 2018-07-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180717_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='shipper_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
