# Generated by Django 2.0.7 on 2018-07-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20180717_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippers', to='customer.Principal'),
        ),
    ]
