# Generated by Django 2.2 on 2019-11-20 09:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_transport', '0013_auto_20191030_1630'),
        ('truck', '0004_auto_20191031_1803'),
        ('employee', '0005_auto_20191031_1802'),
        ('booking', '0023_auto_20191116_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSummaryDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('co', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clear_date', models.DateField(blank=True, default=None, null=True)),
                ('work_date', models.DateField(blank=True, default=None, null=True)),
                ('order_type', models.CharField(blank=True, max_length=5, null=True)),
                ('double_container', models.BooleanField(default=False)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('price', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Driver')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck.Truck')),
                ('work_agent_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_transport.AgentTransport')),
                ('work_normal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_expense', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('cus_expense', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('total_expense', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_report.WorkOrder')),
            ],
        ),
    ]
