# Generated by Django 2.2 on 2020-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_report', '0002_expensesummarydate_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
