# Generated by Django 2.1 on 2018-09-29 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
                ('agent', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('booking_no', models.CharField(blank=True, max_length=50)),
                ('pickup_tr', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_from', models.CharField(blank=True, default='', max_length=20)),
                ('return_tr', models.CharField(blank=True, default='', max_length=20)),
                ('return_to', models.CharField(blank=True, default='', max_length=20)),
                ('container_1', models.CharField(blank=True, default='', max_length=50)),
                ('container_2', models.CharField(blank=True, default='', max_length=50)),
                ('ref', models.CharField(blank=True, default='', max_length=200)),
                ('remark', models.CharField(blank=True, default='', max_length=200)),
                ('work_type', models.CharField(choices=[('ep', 'Empty'), ('fc', 'Full')], default='ep', max_length=10)),
                ('work_id', models.CharField(blank=True, default='', max_length=50)),
                ('work_number', models.IntegerField(default=1)),
                ('pickup_date', models.DateField(blank=True, default='', null=True)),
                ('return_date', models.DateField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('2', 'Finished'), ('1', '-'), ('0', 'Cancel')], default=1, max_length=1)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Principal')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Shipper')),
            ],
        ),
    ]
