# Generated by Django 2.1 on 2018-12-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0003_auto_20181203_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransport',
            name='operation_type',
            field=models.CharField(choices=[('', '-'), ('export_loaded', 'Export Loaded'), ('import_loaded', 'Import Loaded'), ('export_empty', 'Export Empty'), ('import_empty', 'Import Empty')], default='', max_length=15),
        ),
    ]
