# Generated by Django 2.1.5 on 2019-01-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0004_auto_20181218_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransport',
            name='summary_status',
            field=models.CharField(choices=[('1', 'Done'), ('0', '-')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
