# Generated by Django 2.2 on 2019-05-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0008_auto_20190420_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransport',
            name='status',
            field=models.CharField(choices=[('4', 'Return'), ('3', 'Pickup'), ('2', 'Completed'), ('1', '-'), ('0', 'Cancel')], default=1, max_length=1),
        ),
    ]
