# Generated by Django 2.1 on 2018-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0008_auto_20180926_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttransport',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agenttransport',
            name='address_other',
        ),
        migrations.RemoveField(
            model_name='agenttransport',
            name='cancel',
        ),
        migrations.AddField(
            model_name='agenttransport',
            name='status',
            field=models.CharField(choices=[('2', 'Finished'), ('1', '-'), ('0', 'Cancel')], default=0, max_length=1),
        ),
    ]
