# Generated by Django 2.1 on 2018-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0009_auto_20180929_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransport',
            name='status',
            field=models.CharField(choices=[('2', 'Finished'), ('1', '-'), ('0', 'Cancel')], default=1, max_length=1),
        ),
    ]
