# Generated by Django 2.2 on 2019-06-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0011_auto_20190515_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransport',
            name='yard_ndd',
            field=models.CharField(choices=[('2', 'Yard'), ('1', 'NDD'), ('0', '-')], default=0, max_length=1),
        ),
    ]
