# Generated by Django 2.2 on 2019-10-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0012_agenttransport_yard_ndd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransport',
            name='agent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='booking_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='container_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='container_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='pickup_tr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='return_tr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='size',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='work_id',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='agenttransport',
            name='work_type',
            field=models.CharField(choices=[('ep', 'Empty'), ('fc', 'Full')], default='ep', max_length=2),
        ),
    ]
