# Generated by Django 2.0.7 on 2018-07-09 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('principal', models.CharField(blank=True, max_length=200)),
                ('shipper', models.CharField(blank=True, max_length=200)),
                ('agent', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=200)),
                ('booking_no', models.CharField(blank=True, max_length=200)),
                ('fw_tr', models.CharField(blank=True, max_length=200)),
                ('fw_fm', models.CharField(blank=True, max_length=200)),
                ('container_no', models.CharField(blank=True, max_length=200)),
                ('seal_no', models.CharField(blank=True, max_length=200)),
                ('bw_tr', models.CharField(blank=True, max_length=200)),
                ('bw_to', models.CharField(blank=True, max_length=200)),
                ('vessel', models.CharField(blank=True, max_length=200)),
                ('port', models.CharField(blank=True, max_length=200)),
                ('closing_time', models.CharField(blank=True, max_length=200)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('loading', models.CharField(blank=True, max_length=200)),
                ('work_id', models.CharField(blank=True, max_length=200)),
                ('pickup_date', models.DateField(blank=True)),
                ('factory_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True)),
            ],
        ),
    ]
