# Generated by Django 2.0.7 on 2018-07-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='principal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shipper',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
