# Generated by Django 2.0.7 on 2018-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180709_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
