# Generated by Django 2.0.7 on 2018-07-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180716_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address_other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
