# Generated by Django 2.0.7 on 2018-07-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180717_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='principal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.Principal'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shipper',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.Shipper'),
        ),
    ]
