# Generated by Django 2.0.7 on 2018-07-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_address_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20),
        ),
    ]
