# Generated by Django 2.0.7 on 2018-07-17 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20180717_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='principal',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='customer.Principal'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shipper',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='customer.Shipper'),
        ),
    ]
