# Generated by Django 2.0.7 on 2018-07-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20180716_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='template_pdf',
        ),
    ]
