# Generated by Django 2.0.7 on 2018-07-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20180717_1148'),
    ]

    operations = [
    ]
