# Generated by Django 2.0.7 on 2018-07-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_shipper'),
    ]

    operations = [
    ]
