# Generated by Django 2.0.7 on 2018-07-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180717_1323'),
        ('booking', '0015_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='principal_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Principal'),
        ),
        migrations.AddField(
            model_name='booking',
            name='shipper_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Shipper'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='principal',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='shipper',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
