# Generated by Django 2.0.7 on 2018-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20180717_1324'),
    ]

    operations = [
    ]
