# Generated by Django 2.0.7 on 2018-07-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_transfer_principal_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='shipper',
        ),
    ]
