# Generated by Django 2.0.7 on 2018-07-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20180717_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='principal_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Principal'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shipper_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Shipper'),
        ),
    ]
