# Generated by Django 2.0.7 on 2018-07-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20180717_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='principal_name',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='shipper_name',
            new_name='shipper',
        ),
    ]
