# Generated by Django 2.2 on 2019-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number',
            field=models.CharField(blank=True, default='0', max_length=2, null=True),
        ),
    ]
