# Generated by Django 2.2 on 2019-07-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='starting_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
