# Generated by Django 2.2 on 2019-08-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_job_starting_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='starting_salary',
        ),
    ]
