# Generated by Django 2.2 on 2020-09-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_name_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='co',
        ),
    ]
