# Generated by Django 2.1 on 2018-09-29 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
                ('agent', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('booking_no', models.CharField(blank=True, max_length=50)),
                ('start', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_tr', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_from', models.CharField(blank=True, default='', max_length=20)),
                ('yard_ndd', models.CharField(choices=[('1', 'NDD'), ('0', '-')], default=0, max_length=1)),
                ('forward_tr', models.CharField(blank=True, default='', max_length=20)),
                ('factory', models.CharField(blank=True, default='', max_length=20)),
                ('backward_tr', models.CharField(blank=True, default='', max_length=20)),
                ('fac_ndd', models.CharField(choices=[('1', 'NDD'), ('0', '-')], default=0, max_length=1)),
                ('return_tr', models.CharField(blank=True, default='', max_length=20)),
                ('return_to', models.CharField(blank=True, default='', max_length=20)),
                ('container_no', models.CharField(blank=True, max_length=50)),
                ('seal_no', models.CharField(blank=True, max_length=50)),
                ('vessel', models.CharField(blank=True, max_length=50)),
                ('port', models.CharField(blank=True, max_length=50)),
                ('closing_date', models.DateField(blank=True, default=None, max_length=20, null=True)),
                ('closing_time', models.CharField(blank=True, max_length=20)),
                ('ref', models.CharField(blank=True, default='', max_length=200)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('work_id', models.CharField(blank=True, max_length=50)),
                ('work_number', models.IntegerField(default=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('factory_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('pickup_in_time', models.CharField(blank=True, default='', max_length=50)),
                ('pickup_out_time', models.CharField(blank=True, default='', max_length=50)),
                ('factory_in_time', models.CharField(blank=True, default='', max_length=50)),
                ('factory_load_start_time', models.CharField(blank=True, default='', max_length=50)),
                ('factory_load_finish_time', models.CharField(blank=True, default='', max_length=50)),
                ('factory_out_time', models.CharField(blank=True, default='', max_length=50)),
                ('return_in_time', models.CharField(blank=True, default='', max_length=50)),
                ('return_out_time', models.CharField(blank=True, default='', max_length=50)),
                ('nextday', models.CharField(choices=[('1', 'Yes'), ('0', '-')], default=0, max_length=1)),
                ('status', models.CharField(choices=[('2', 'Finished'), ('1', '-'), ('0', 'Cancel')], default=1, max_length=1)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Principal')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Shipper')),
            ],
        ),
    ]
