# Generated by Django 2.1 on 2018-10-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20181004_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ref',
        ),
    ]
