# Generated by Django 2.1 on 2018-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fac_ndd',
            field=models.CharField(choices=[('2', 'Fac'), ('1', 'NDD'), ('0', '-')], default=0, max_length=1),
        ),
    ]
