# Generated by Django 2.1.5 on 2019-01-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20181106_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='summary_status',
            field=models.CharField(choices=[('1', 'Done'), ('0', '-')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
