# Generated by Django 2.1.5 on 2019-03-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190306_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='factory_in_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='factory_load_finish_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='factory_load_start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='factory_out_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_in_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_out_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_in_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_out_time',
        ),
    ]
