# Generated by Django 2.1.5 on 2019-03-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190306_1726'),
        ('booking', '0006_booking_summary_status'),
    ]

    operations = [
    ]
