# Generated by Django 2.1.5 on 2019-03-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_merge_20190311_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_no',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='factory',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_from',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='remark',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_to',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vessel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
