# Generated by Django 2.2 on 2019-04-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20190315_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='summary_status',
            field=models.CharField(blank=True, choices=[('1', 'Done'), ('0', '-')], max_length=1, null=True),
        ),
    ]
