# Generated by Django 2.2 on 2019-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20190403_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('4', 'Factory'), ('3', 'Yard'), ('2', 'Finished'), ('1', '-'), ('0', 'Cancel')], default=1, max_length=1),
        ),
    ]
