# Generated by Django 2.2 on 2019-05-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20190418_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start',
        ),
    ]
