# Generated by Django 2.2 on 2019-05-14 04:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20190514_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='color',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fac_ndd',
            field=models.CharField(choices=[('3', 'Yard'), ('2', 'Fac'), ('1', 'NDD'), ('0', '-')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='yard_ndd',
            field=models.CharField(choices=[('2', 'Yard'), ('1', 'NDD'), ('0', '-')], default=0, max_length=1),
        ),
    ]
