# Generated by Django 2.2 on 2019-05-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20190515_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10)),
                ('num', models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=1)),
            ],
        ),
    ]
