# Generated by Django 2.2 on 2019-10-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_containersize'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtime',
            name='key',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='time',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
