# Generated by Django 2.2 on 2019-10-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20191029_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='backward_tr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='closing_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='closing_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='container_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='forward_tr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_tr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_tr',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seal_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='size',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tare',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='work_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
