# Generated by Django 2.1 on 2018-09-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20180929_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fac_ndd',
            field=models.CharField(choices=[('1', 'NDD'), ('0', '-')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='yard_ndd',
            field=models.CharField(choices=[('1', 'NDD'), ('0', '-')], default=0, max_length=1),
        ),
    ]
