# Generated by Django 2.2 on 2019-11-14 09:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20191030_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtime',
            name='factory_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='pickup_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='return_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
