# Generated by Django 2.1 on 2018-10-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_shipperaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='address',
        ),
    ]
