# Generated by Django 2.2 on 2019-10-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_shipper_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='shipperaddress',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shipperaddress',
            name='address_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
