# Generated by Django 2.1 on 2018-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180906_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
