# Generated by Django 2.2 on 2019-08-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='pat_pass_expired_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
