# Generated by Django 2.2 on 2019-08-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
