# Generated by Django 2.2 on 2019-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmanufacturer',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
