# Generated by Django 2.2 on 2019-08-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TruckManufacturer',
            new_name='Manufacturer',
        ),
    ]
