# Generated by Django 2.2 on 2019-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_auto_20190829_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='owner',
            field=models.CharField(blank=True, default='ndd', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='owner',
            field=models.CharField(blank=True, default='ndd', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
