# Generated by Django 2.2 on 2019-10-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_auto_20191007_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
