# Generated by Django 2.2 on 2020-09-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_auto_20191031_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='owner',
        ),
    ]
